- name: await solman
  raw: curl localhost/solutionmanager/api/v1/solutions
  register: result
  until: not ('503 Service Unavailable' in result.stdout)
  retries: 15
  delay: 3
  check_mode: false
- name: get solutions
  raw: curl localhost/solutionmanager/api/v1/solutions
  register: result
  until: ('items' in result.stdout)
  retries: 2
  delay: 5
  check_mode: false
- name: set installed solutions fact
  vars:
    tmp: "{{ result.stdout }}"
  set_fact:
    blueplanet_solution_installed: "{{ blueplanet_solution_installed + [ { 'SolutionType': item.SolutionType, 'Version': item.Version } ] }}"
  with_items: "{{ tmp['items'] }}"
  when: tmp['items'] is defined
- name: set installed solutions full fact
  vars:
    tmp: "{{ result.stdout }}"
  set_fact:
    blueplanet_solution_installed_full: "{{ tmp['items'] }}"
  when: tmp['items'] is defined
- name: print blueplanet_solution_installed
  debug:
    var: blueplanet_solution_installed
