- name: get solutions
  raw: curl localhost/solutionmanager/api/v1/solutions
  register: result
  until: not ('503 Service Unavailable' in result.stdout)
  retries: 5
  delay: 3
- name: set solutions fact
  set_fact:
    solutions: "{{ result.stdout }}"
- name: print solutions
  debug:
    var: solutions
