---
# tasks file for blueplanet-solution-deploy
- name: read lineup
  import_tasks: read_lineup.yml
  tags:
    - always
- name: Set Registry
  become: true
  import_tasks: set_registry.yml
  tags:
    - registry
- name: get installed solutions
  import_tasks: get_solutions.yml
  tags:
    - deploy
- name: get get_solutions_deployed
  import_tasks: get_solutions_deployed.yml
  tags:
    - deploy
- name: build desired list
  import_tasks: generate_solution_list.yml
  tags:
    - deploy
- name: Purge non-matching solutions
  vars:
    purge_list: "{{ blueplanet_solution_installed | difference(blueplanet_solution_desired) }}"
  include_tasks: solution_purge.yml
  tags:
    - deploy
  loop: "{{ purge_list }}"
  loop_control:
    loop_var: outer_item

- name: Deploy Solutions
  vars:
    deploy_list: "{{ blueplanet_solution_desired | difference(blueplanet_solution_installed) }}"
  include_tasks: solution_deploy.yml
  loop: "{{ deploy_list }}"
  loop_control:
    loop_var: outer_item
